
[build]
  publish = "public/"
  functions = "api/"
  ignore = "git diff --quiet HEAD^ HEAD ../../"

[[redirects]]
  # SSR and SPA
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  
  # SPA only
  # from = "/*"
  # to = "/__app.html"
  # status = 200

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"